export default {
  "login": "NateOs",
  "id": 22566659,
  "node_id": "MDQ6VXNlcjIyNTY2NjU5",
  "avatar_url": "https://avatars.githubusercontent.com/u/22566659?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/NateOs",
  "html_url": "https://github.com/NateOs",
  "followers_url": "https://api.github.com/users/NateOs/followers",
  "following_url": "https://api.github.com/users/NateOs/following{/other_user}",
  "gists_url": "https://api.github.com/users/NateOs/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/NateOs/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/NateOs/subscriptions",
  "organizations_url": "https://api.github.com/users/NateOs/orgs",
  "repos_url": "https://api.github.com/users/NateOs/repos",
  "events_url": "https://api.github.com/users/NateOs/events{/privacy}",
  "received_events_url": "https://api.github.com/users/NateOs/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Sodja Nathan  O.",
  "company": "Currently Searching...",
  "blog": "Soon.",
  "location": "Accra",
  "email": null,
  "hireable": true,
  "bio": "Web Dev, gonna make every line of code count!",
  "twitter_username": "me_souljah",
  "public_repos": 53,
  "public_gists": 0,
  "followers": 0,
  "following": 15,
  "created_at": "2016-10-01T21:00:16Z",
  "updated_at": "2021-03-29T19:22:35Z"
};
